# App Name
spring.application.name=backTester

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/nl_backtester
spring.datasource.username=postgres
spring.datasource.password=Vishva@2003

# Hibernate properties to automatically create tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Python Microservice Connection Endpoint
python.engine.url=http://localhost:8000/api/v1/backtest